Fix Python CI workflow success logic

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -84,7 +84,8 @@ jobs:
   publish-to-pypi:
     name: >-
       Publish Python 🐍 distribution 📦 to PyPI
-    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
+    if: startsWith(github.ref, 'refs/tags/software')  # only publish to PyPI on tag pushes
+    continue-on-error: true
     needs:
     - build
     runs-on: ubuntu-latest
@@ -107,6 +108,7 @@ jobs:
 
   publish-to-testpypi:
     name: Publish Python 🐍 distribution 📦 to TestPyPI
+    continue-on-error: true
     needs:
     - build
     runs-on: ubuntu-latest
@@ -173,3 +175,30 @@ jobs:
         gh release upload
         '${{ github.ref_name }}' dist/**
         --repo '${{ github.repository }}'
+
+  check_results:
+    name: Check pypi deployment results
+    runs-on: ubuntu-latest
+    needs: [publish-to-pypi, publish-to-testpypi]
+    if: always()     # run even if previous failed
+    steps:
+      - name: Decide workflow result
+        run: |
+          RESULT1="${{ needs.publish-to-pypi.result }}"
+          RESULT2="${{ needs.publish-to-testpypi.result }}"
+
+          echo "Publish to pypi: $RESULT1"
+          echo "Publish to test-pypi: $RESULT2"
+
+          if [[ "$RESULT1" == "success" ]]; then
+            echo "Publish to pypi succeeded → workflow passes"
+            exit 0
+          fi
+
+          if [[ "$RESULT1" == "skipped" && "$RESULT2" == "success" ]]; then
+            echo "Publish to pypi skipped but publish to test-pypi succeeded → workflow passes"
+            exit 0
+          fi
+
+          echo "workflow failed"
+          exit 1
